# ==============================================================================
# T-MoE Infrastructure — Terraform Outputs
# ==============================================================================
# Key infrastructure values for application configuration.
# Use `terraform output` to retrieve values after `terraform apply`.
# ==============================================================================

output "raw_data_bucket_name" {
  description = "Name of the S3 bucket for raw data landing"
  value       = aws_s3_bucket.raw_data.id
}

output "raw_data_bucket_arn" {
  description = "ARN of the S3 bucket for raw data landing"
  value       = aws_s3_bucket.raw_data.arn
}

output "sagemaker_execution_role_arn" {
  description = "ARN of the SageMaker execution role"
  value       = aws_iam_role.sagemaker_execution.arn
}

output "sagemaker_execution_role_name" {
  description = "Name of the SageMaker execution role"
  value       = aws_iam_role.sagemaker_execution.name
}

output "cloudwatch_log_group" {
  description = "CloudWatch log group for SageMaker processing jobs"
  value       = aws_cloudwatch_log_group.sagemaker_processing.name
}

output "aws_region" {
  description = "AWS region where resources are deployed"
  value       = var.aws_region
}

# --- ECR ---
output "ecr_repository_url" {
  description = "ECR repository URL for training Docker image"
  value       = aws_ecr_repository.training.repository_url
}

output "ecr_repository_name" {
  description = "ECR repository name"
  value       = aws_ecr_repository.training.name
}

# --- AWS Batch ---
output "batch_job_queue_arn" {
  description = "ARN of the Batch training job queue"
  value       = aws_batch_job_queue.training.arn
}

output "batch_job_queue_name" {
  description = "Name of the Batch training job queue"
  value       = aws_batch_job_queue.training.name
}

output "batch_job_definition_arn" {
  description = "ARN of the Batch training job definition"
  value       = aws_batch_job_definition.training.arn
}

output "batch_compute_environment_arn" {
  description = "ARN of the Batch GPU Spot compute environment"
  value       = aws_batch_compute_environment.gpu_spot.arn
}

output "batch_log_group" {
  description = "CloudWatch log group for Batch training jobs"
  value       = aws_cloudwatch_log_group.batch_training.name
}

# --- VPC ---
output "batch_vpc_id" {
  description = "VPC ID for Batch compute environment"
  value       = aws_vpc.batch.id
}

# --- Environment Configuration Snippet ---
# Run `terraform output env_configuration` to get ready-to-use .env content
output "env_configuration" {
  description = "Environment variable configuration for training pipeline"
  value       = <<-EOT
    # === T-MoE Training Pipeline Environment Configuration ===
    # Generated by: terraform output env_configuration
    AWS_REGION=${var.aws_region}
    SAGEMAKER_ROLE_ARN=${aws_iam_role.sagemaker_execution.arn}
    RAW_DATA_BUCKET=${aws_s3_bucket.raw_data.id}
    ENVIRONMENT=${var.environment}
    ECR_REPOSITORY_URL=${aws_ecr_repository.training.repository_url}
    BATCH_JOB_QUEUE=${aws_batch_job_queue.training.name}
    BATCH_JOB_DEFINITION=${aws_batch_job_definition.training.name}
    BATCH_LOG_GROUP=${aws_cloudwatch_log_group.batch_training.name}
    LOG_LEVEL=INFO
  EOT
}

