# ==============================================================================
# T-MoE Data Ingestion - Terraform Outputs
# ==============================================================================
# Key infrastructure values for application configuration.
# Use `terraform output` to retrieve values after `terraform apply`.
# ==============================================================================

output "raw_data_bucket_name" {
  description = "Name of the S3 bucket for raw data landing"
  value       = aws_s3_bucket.raw_data.id
}

output "raw_data_bucket_arn" {
  description = "ARN of the S3 bucket for raw data landing"
  value       = aws_s3_bucket.raw_data.arn
}

output "sagemaker_execution_role_arn" {
  description = "ARN of the SageMaker execution role"
  value       = aws_iam_role.sagemaker_execution.arn
}

output "sagemaker_execution_role_name" {
  description = "Name of the SageMaker execution role"
  value       = aws_iam_role.sagemaker_execution.name
}

output "cloudwatch_log_group" {
  description = "CloudWatch log group for SageMaker processing jobs"
  value       = aws_cloudwatch_log_group.sagemaker_processing.name
}

output "aws_region" {
  description = "AWS region where resources are deployed"
  value       = var.aws_region
}

# --- Environment Configuration Snippet ---
# Run `terraform output env_configuration` to get ready-to-use .env content
output "env_configuration" {
  description = "Environment variable configuration for data ingestion scripts"
  value       = <<-EOT
    # === T-MoE Data Ingestion Environment Configuration ===
    # Generated by: terraform output env_configuration
    AWS_REGION=${var.aws_region}
    SAGEMAKER_ROLE_ARN=${aws_iam_role.sagemaker_execution.arn}
    RAW_DATA_BUCKET=${aws_s3_bucket.raw_data.id}
    ENVIRONMENT=${var.environment}
    LOG_LEVEL=INFO
  EOT
}
